### ISSUE TITLE
`WordNode`s sometimes contain ending punctuation.

### ISSUE THREAD

**Issue by josiahsprague** [wooorm/nlcst#4]
I'm having a hard time tracking down exactly where this bug is, but I'm having trouble when running documents through retext-spell, because the `WordNode`s being passed in sometimes contain the ending punctuation which makes the word get flagged for being misspelled. For example, I've got the following markdown;

```markdown
This tool uses [retext](https://github.com/wooorm/retext) to check the quality of writing in your project's documentation using these plugins;

* [remark-lint](https://github.com/wooorm/remark-lint) checks for proper markdown formatting.
* [retext-readability](https://github.com/wooorm/retext-readability) checks the reading level of the whole document.
* [retext-simplify](https://github.com/wooorm/retext-simplify) warns on over-complicated phrases.
* [retext-equality](https://github.com/wooorm/retext-equality) warns on insensitive, inconsiderate language.
* [retext-intensify](https://github.com/wooorm/retext-intensify) warns on filler, weasel and hedge words.
```

I'm passing it through `retext().use(spell)` [here](https://github.com/SparkartGroupInc/quality-docs/blob/add-spelling/index.js#L65-L78) and when the tree is passed through `retext-spell`, I'm getting `WordNode`s that look like this;

```js
{ type: 'WordNode',
  children:
   [ { type: 'TextNode', value: 'language', position: [Object] },
     { type: 'PunctuationNode', value: '.', position: [Object] } ],
  position:
   { start: { line: 81, column: 100, offset: 2580 },
     end: { line: 81, column: 109, offset: 2589 } } }
```

Finally, doing `toString(node)` for these nodes returns the following strings which fail the spell check; `formatting.`, `document.`, `phrases.`, `language.`. For some reason the last node doesn't include the ending punctuation.

Any idea what might be going on here and which module a fix should be applied in? I know I could do something like this to work around the problem by modifying nodes with ending punctuation in retext-spell;
```js
// If the last WordNode child is a PunctuationNode, remove it
if (node.children[node.children.length-1].type == 'PunctuationNode') {
    node.children.pop();
}
```

But that doesn't seem like the correct place to correct the problem.

Thoughts?

**Comment by wooorm** [comment]
Oh darn, thanks for raising that up! I’m guessing somewhere [here, in `mdast-util-to-nlcst`](https://github.com/wooorm/mdast-util-to-nlcst/blob/900a2183a5ee54b82dde888c311f16cbe654b453/index.js#L164), or even deeper down.

Could you confirm if you’re seeing with both `retext-english` (which uses `parse-english`) and `retext-latin` (which uses `parse-latin`, and is the default `retext` parser)?

**Comment by josiahsprague** [comment]
Sure, let me verify with both.

**Comment by josiahsprague** [comment]
Just confirmed. I'm seeing the problem with `retext.use(english)` and `retext.use(latin)`.

**Comment by wooorm** [comment]
Ah, well I remember the reasoning!

Well, there’s no sentence-casing, and that makes it really hard to detect them.

```
Could you buy:

* milk.
* eggs.
* whiskey.
```

```
Some common abbreviations are:

* mr.
* mrs.
* gov.
```

```
Some iOS versions are:

* iOS 5.
* iOS 6.
* iOS 7.
```


```
These are clearly sentences:

* Zero sentences.
* One sentence.
* Two sentences.
```

```
These are also sentences:

* zero sentences.

* one sentence.

* two sentences.
```

What should happen where?

**Comment by josiahsprague** [comment]
Ah, I see. Yeah, that's tricky. Maybe the right solution is more robust code in `retext-spell`.

**Comment by wooorm** [comment]
Maybe we could, if a word ends in a dot, check spelling twice, once with and once without. Same goes for words with dashes maybe, where we check the whole thing together first, if that fails each part on its own.

**Comment by josiahsprague** [comment]
Yeah, I was thinking something along those lines, but ran into the problem of what to do with hyphenated words that shouldn't be, like `unnecessarily-hyphenated`. Maybe that shouldn't be detected. I noticed it's not flagged by my browser.

**Comment by josiahsprague** [comment]
So, this is really code that would belong in `retext-spell`, but I think that makes sense; first testing the whole `WordNode` and if that fails, testing each of it's `TextNode`s individually.

**Comment by wooorm** [comment]
👍 

Let’s continue this discussion in wooorm/retext-spell#6, which me-thinks is moving to include more than just digits.
